channels:
- conda-forge
dependencies:
- python=3.13.5
- pip<=25.1.1
- pip:
  - mlflow==3.10.0
  - cloudpickle==3.1.2
  - numpy==2.3.1
  - pandas==2.3.1
  - psutil==7.0.0
  - pyarrow==23.0.1
  - scikit-learn==1.8.0
  - scipy==1.17.0
name: mlflow-env
